import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { ethers } from "ethers";
import { SiweMessage } from "siwe";
import { useSignMessage, useSigner, useProvider, useAccount } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { address } = useAccount();
  const { data: signer } = useSigner();
  const {
    data: SignData,
    isError,
    isLoading,
    isSuccess,
    signMessage,
  } = useSignMessage({
    message: "gm wagmi frens",
  });
  const domain = window.location.host;
  const origin = window.location.origin;

  console.log(SignData);

  function createSiweMessage(address, statement) {
    const message = new SiweMessage({
      domain,
      address,
      statement,
      uri: origin,
      version: "1",
      chainId: "80001",
    });
    return message.prepareMessage();
  }
  const signMessageWithETH = async () => {
    try {
      const message = createSiweMessage(
        address,
        "Sign in with ETH into the App"
      );
      console.log(await signer.signMessage(message));
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Sigin with Ethereum Demo</p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By @0xdhruv
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <ConnectButton />
          <button onClick={() => signMessage()}> Sign Wagmi Message</button>
          <button onClick={() => signMessageWithETH()}>
            {" "}
            Sign SIWE Message
          </button>
        </div>
      </main>
    </>
  );
}
